server:
  port: 9901
spring:
  application:
    name: config-server-bus-kafka
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Vistey/test-config.git
    stream:
      binders:
        zk-nodes: localhost
        brokers: localhost
    bus:
      trace:
        enabled: false
management:
  security:
    enabled: false
